/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

import (
	"time"
)

type WritableDeviceWithConfigContext struct {
	Id int32 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	DisplayName string `json:"display_name,omitempty"`
	DeviceType int32 `json:"device_type"`
	DeviceRole int32 `json:"device_role"`
	Tenant int32 `json:"tenant,omitempty"`
	Platform int32 `json:"platform,omitempty"`
	Serial string `json:"serial,omitempty"`
	// A unique tag used to identify this device
	AssetTag string `json:"asset_tag,omitempty"`
	Site int32 `json:"site"`
	Rack int32 `json:"rack,omitempty"`
	// The lowest-numbered unit occupied by the device
	Position int32 `json:"position,omitempty"`
	Face string `json:"face,omitempty"`
	ParentDevice *NestedDevice `json:"parent_device,omitempty"`
	Status string `json:"status,omitempty"`
	PrimaryIp string `json:"primary_ip,omitempty"`
	PrimaryIp4 int32 `json:"primary_ip4,omitempty"`
	PrimaryIp6 int32 `json:"primary_ip6,omitempty"`
	Cluster int32 `json:"cluster,omitempty"`
	VirtualChassis int32 `json:"virtual_chassis,omitempty"`
	VcPosition int32 `json:"vc_position,omitempty"`
	VcPriority int32 `json:"vc_priority,omitempty"`
	Comments string `json:"comments,omitempty"`
	LocalContextData string `json:"local_context_data,omitempty"`
	Tags []string `json:"tags,omitempty"`
	CustomFields *interface{} `json:"custom_fields,omitempty"`
	ConfigContext map[string]string `json:"config_context,omitempty"`
	Created string `json:"created,omitempty"`
	LastUpdated time.Time `json:"last_updated,omitempty"`
}
