/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

type PowerPort struct {
	Id int32 `json:"id,omitempty"`
	Device *NestedDevice `json:"device"`
	Name string `json:"name"`
	Type_ *Type3 `json:"type,omitempty"`
	// Maximum power draw (watts)
	MaximumDraw int32 `json:"maximum_draw,omitempty"`
	// Allocated power draw (watts)
	AllocatedDraw int32 `json:"allocated_draw,omitempty"`
	Description string `json:"description,omitempty"`
	ConnectedEndpointType string `json:"connected_endpoint_type,omitempty"`
	//  Return the appropriate serializer for the type of connected object. 
	ConnectedEndpoint map[string]string `json:"connected_endpoint,omitempty"`
	ConnectionStatus *ConnectionStatus `json:"connection_status,omitempty"`
	Cable *NestedCable `json:"cable,omitempty"`
	Tags []string `json:"tags,omitempty"`
}
