/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.11
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

type WritableCustomField struct {
	Id int32 `json:"id,omitempty"`
	Url string `json:"url,omitempty"`
	Display string `json:"display,omitempty"`
	ContentTypes []string `json:"content_types"`
	Type_ string `json:"type,omitempty"`
	// Internal field name
	Name string `json:"name"`
	// Name of the field as displayed to users (if not provided, the field's name will be used)
	Label string `json:"label,omitempty"`
	Description string `json:"description,omitempty"`
	// If true, this field is required when creating new objects or editing an existing object.
	Required bool `json:"required,omitempty"`
	// Loose matches any instance of a given string; exact matches the entire field.
	FilterLogic string `json:"filter_logic,omitempty"`
	// Default value for the field (must be a JSON value). Encapsulate strings with double quotes (e.g. \"Foo\").
	Default_ string `json:"default,omitempty"`
	// Fields with higher weights appear lower in a form.
	Weight int32 `json:"weight,omitempty"`
	// Minimum allowed value (for numeric fields)
	ValidationMinimum int32 `json:"validation_minimum,omitempty"`
	// Maximum allowed value (for numeric fields)
	ValidationMaximum int32 `json:"validation_maximum,omitempty"`
	// Regular expression to enforce on text field values. Use ^ and $ to force matching of entire string. For example, <code>^[A-Z]{3}$</code> will limit values to exactly three uppercase letters.
	ValidationRegex string `json:"validation_regex,omitempty"`
	// Comma-separated list of available choices (for selection fields)
	Choices []string `json:"choices,omitempty"`
}
