/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

type WritableVirtualChassis struct {
	Id int32 `json:"id,omitempty"`
	Master int32 `json:"master"`
	Domain string `json:"domain,omitempty"`
	Tags []string `json:"tags,omitempty"`
	MemberCount int32 `json:"member_count,omitempty"`
}
