/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.11
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

type WritableObjectPermission struct {
	Id int32 `json:"id,omitempty"`
	Url string `json:"url,omitempty"`
	Display string `json:"display,omitempty"`
	Name string `json:"name"`
	Description string `json:"description,omitempty"`
	Enabled bool `json:"enabled,omitempty"`
	ObjectTypes []string `json:"object_types"`
	Groups []int32 `json:"groups,omitempty"`
	Users []int32 `json:"users,omitempty"`
	// The list of actions granted by this permission
	Actions []string `json:"actions"`
	// Queryset filter matching the applicable objects of the selected type(s)
	Constraints string `json:"constraints,omitempty"`
}
