/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.11
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

type NestedDeviceType struct {
	Id int32 `json:"id,omitempty"`
	Url string `json:"url,omitempty"`
	Display string `json:"display,omitempty"`
	Manufacturer *NestedManufacturer `json:"manufacturer,omitempty"`
	Model string `json:"model"`
	Slug string `json:"slug"`
	DisplayName string `json:"display_name,omitempty"`
	DeviceCount int32 `json:"device_count,omitempty"`
}
