/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

type WritableRackReservation struct {
	Id int32 `json:"id,omitempty"`
	Rack int32 `json:"rack"`
	Units []int32 `json:"units"`
	Created string `json:"created,omitempty"`
	User int32 `json:"user"`
	Tenant int32 `json:"tenant,omitempty"`
	Description string `json:"description"`
}
