/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

type WritableFrontPortTemplate struct {
	Id int32 `json:"id,omitempty"`
	DeviceType int32 `json:"device_type"`
	Name string `json:"name"`
	Type_ string `json:"type"`
	RearPort int32 `json:"rear_port"`
	RearPortPosition int32 `json:"rear_port_position,omitempty"`
}
