/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

import (
	"time"
)

type Cluster struct {
	Id int32 `json:"id,omitempty"`
	Name string `json:"name"`
	Type_ *NestedClusterType `json:"type"`
	Group *NestedClusterGroup `json:"group,omitempty"`
	Tenant *NestedTenant `json:"tenant,omitempty"`
	Site *NestedSite `json:"site,omitempty"`
	Comments string `json:"comments,omitempty"`
	Tags []string `json:"tags,omitempty"`
	CustomFields *interface{} `json:"custom_fields,omitempty"`
	Created string `json:"created,omitempty"`
	LastUpdated time.Time `json:"last_updated,omitempty"`
	DeviceCount int32 `json:"device_count,omitempty"`
	VirtualmachineCount int32 `json:"virtualmachine_count,omitempty"`
}
