/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.11
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

import (
	"time"
)

type WritableIpAddress struct {
	Id int32 `json:"id,omitempty"`
	Url string `json:"url,omitempty"`
	Display string `json:"display,omitempty"`
	Family string `json:"family,omitempty"`
	// IPv4 or IPv6 address (with mask)
	Address string `json:"address"`
	Vrf int32 `json:"vrf,omitempty"`
	Tenant int32 `json:"tenant,omitempty"`
	// The operational status of this IP
	Status string `json:"status,omitempty"`
	// The functional role of this IP
	Role string `json:"role,omitempty"`
	AssignedObjectType string `json:"assigned_object_type,omitempty"`
	AssignedObjectId int32 `json:"assigned_object_id,omitempty"`
	AssignedObject map[string]string `json:"assigned_object,omitempty"`
	// The IP for which this address is the \"outside\" IP
	NatInside int32 `json:"nat_inside,omitempty"`
	NatOutside string `json:"nat_outside,omitempty"`
	// Hostname or FQDN (not case-sensitive)
	DnsName string `json:"dns_name,omitempty"`
	Description string `json:"description,omitempty"`
	Tags []NestedTag `json:"tags,omitempty"`
	CustomFields *interface{} `json:"custom_fields,omitempty"`
	Created string `json:"created,omitempty"`
	LastUpdated time.Time `json:"last_updated,omitempty"`
}
