/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

import (
	"time"
)

type Vlan struct {
	Id int32 `json:"id,omitempty"`
	Site *NestedSite `json:"site,omitempty"`
	Group *NestedVlanGroup `json:"group,omitempty"`
	Vid int32 `json:"vid"`
	Name string `json:"name"`
	Tenant *NestedTenant `json:"tenant,omitempty"`
	Status *Status8 `json:"status,omitempty"`
	Role *NestedRole `json:"role,omitempty"`
	Description string `json:"description,omitempty"`
	Tags []string `json:"tags,omitempty"`
	DisplayName string `json:"display_name,omitempty"`
	CustomFields *interface{} `json:"custom_fields,omitempty"`
	Created string `json:"created,omitempty"`
	LastUpdated time.Time `json:"last_updated,omitempty"`
	PrefixCount int32 `json:"prefix_count,omitempty"`
}
