/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

type ConfigContext struct {
	Id int32 `json:"id,omitempty"`
	Name string `json:"name"`
	Weight int32 `json:"weight,omitempty"`
	Description string `json:"description,omitempty"`
	IsActive bool `json:"is_active,omitempty"`
	Regions []NestedRegion `json:"regions,omitempty"`
	Sites []NestedSite `json:"sites,omitempty"`
	Roles []NestedDeviceRole `json:"roles,omitempty"`
	Platforms []NestedPlatform `json:"platforms,omitempty"`
	ClusterGroups []NestedClusterGroup `json:"cluster_groups,omitempty"`
	Clusters []NestedCluster `json:"clusters,omitempty"`
	TenantGroups []NestedTenantGroup `json:"tenant_groups,omitempty"`
	Tenants []NestedTenant `json:"tenants,omitempty"`
	Tags []string `json:"tags,omitempty"`
	Data string `json:"data"`
}
