/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

import (
	"time"
)

type Provider struct {
	Id int32 `json:"id,omitempty"`
	Name string `json:"name"`
	Slug string `json:"slug"`
	// 32-bit autonomous system number
	Asn int32 `json:"asn,omitempty"`
	Account string `json:"account,omitempty"`
	PortalUrl string `json:"portal_url,omitempty"`
	NocContact string `json:"noc_contact,omitempty"`
	AdminContact string `json:"admin_contact,omitempty"`
	Comments string `json:"comments,omitempty"`
	Tags []string `json:"tags,omitempty"`
	CustomFields *interface{} `json:"custom_fields,omitempty"`
	Created string `json:"created,omitempty"`
	LastUpdated time.Time `json:"last_updated,omitempty"`
	CircuitCount int32 `json:"circuit_count,omitempty"`
}
