/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

import (
	"time"
)

type Vrf struct {
	Id int32 `json:"id,omitempty"`
	Name string `json:"name"`
	// Unique route distinguisher (as defined in RFC 4364)
	Rd string `json:"rd,omitempty"`
	Tenant *NestedTenant `json:"tenant,omitempty"`
	// Prevent duplicate prefixes/IP addresses within this VRF
	EnforceUnique bool `json:"enforce_unique,omitempty"`
	Description string `json:"description,omitempty"`
	Tags []string `json:"tags,omitempty"`
	DisplayName string `json:"display_name,omitempty"`
	CustomFields *interface{} `json:"custom_fields,omitempty"`
	Created string `json:"created,omitempty"`
	LastUpdated time.Time `json:"last_updated,omitempty"`
	IpaddressCount int32 `json:"ipaddress_count,omitempty"`
	PrefixCount int32 `json:"prefix_count,omitempty"`
}
