/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.11
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

import (
	"time"
)

type WritablePowerFeed struct {
	Id int32 `json:"id,omitempty"`
	Url string `json:"url,omitempty"`
	Display string `json:"display,omitempty"`
	PowerPanel int32 `json:"power_panel"`
	Rack int32 `json:"rack,omitempty"`
	Name string `json:"name"`
	Status string `json:"status,omitempty"`
	Type_ string `json:"type,omitempty"`
	Supply string `json:"supply,omitempty"`
	Phase string `json:"phase,omitempty"`
	Voltage int32 `json:"voltage,omitempty"`
	Amperage int32 `json:"amperage,omitempty"`
	// Maximum permissible draw (percentage)
	MaxUtilization int32 `json:"max_utilization,omitempty"`
	Comments string `json:"comments,omitempty"`
	// Treat as if a cable is connected
	MarkConnected bool `json:"mark_connected,omitempty"`
	Cable *NestedCable `json:"cable,omitempty"`
	//  Return the appropriate serializer for the cable termination model. 
	CablePeer map[string]string `json:"cable_peer,omitempty"`
	CablePeerType string `json:"cable_peer_type,omitempty"`
	//  Return the appropriate serializer for the type of connected object. 
	ConnectedEndpoint map[string]string `json:"connected_endpoint,omitempty"`
	ConnectedEndpointType string `json:"connected_endpoint_type,omitempty"`
	ConnectedEndpointReachable bool `json:"connected_endpoint_reachable,omitempty"`
	Tags []NestedTag `json:"tags,omitempty"`
	CustomFields *interface{} `json:"custom_fields,omitempty"`
	Created string `json:"created,omitempty"`
	LastUpdated time.Time `json:"last_updated,omitempty"`
	Occupied string `json:"_occupied,omitempty"`
}
