/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

type DeviceBay struct {
	Id int32 `json:"id,omitempty"`
	Device *NestedDevice `json:"device"`
	Name string `json:"name"`
	Description string `json:"description,omitempty"`
	InstalledDevice *NestedDevice `json:"installed_device,omitempty"`
	Tags []string `json:"tags,omitempty"`
}
