/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

type Cable struct {
	Id int32 `json:"id,omitempty"`
	TerminationAType string `json:"termination_a_type"`
	TerminationAId int32 `json:"termination_a_id"`
	TerminationA map[string]string `json:"termination_a,omitempty"`
	TerminationBType string `json:"termination_b_type"`
	TerminationBId int32 `json:"termination_b_id"`
	TerminationB map[string]string `json:"termination_b,omitempty"`
	Type_ string `json:"type,omitempty"`
	Status *Status1 `json:"status,omitempty"`
	Label string `json:"label,omitempty"`
	Color string `json:"color,omitempty"`
	Length int32 `json:"length,omitempty"`
	LengthUnit *LengthUnit `json:"length_unit,omitempty"`
}
