/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

type NestedVirtualChassis struct {
	Id int32 `json:"id,omitempty"`
	Url string `json:"url,omitempty"`
	Master *NestedDevice `json:"master"`
	MemberCount int32 `json:"member_count,omitempty"`
}
