/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.11
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

import (
	"time"
)

type Circuit struct {
	Id int32 `json:"id,omitempty"`
	Url string `json:"url,omitempty"`
	Display string `json:"display,omitempty"`
	Cid string `json:"cid"`
	Provider *NestedProvider `json:"provider"`
	Type_ *NestedCircuitType `json:"type"`
	Status *Status `json:"status,omitempty"`
	Tenant *NestedTenant `json:"tenant,omitempty"`
	InstallDate string `json:"install_date,omitempty"`
	CommitRate int32 `json:"commit_rate,omitempty"`
	Description string `json:"description,omitempty"`
	TerminationA *CircuitCircuitTermination `json:"termination_a,omitempty"`
	TerminationZ *CircuitCircuitTermination `json:"termination_z,omitempty"`
	Comments string `json:"comments,omitempty"`
	Tags []NestedTag `json:"tags,omitempty"`
	CustomFields *interface{} `json:"custom_fields,omitempty"`
	Created string `json:"created,omitempty"`
	LastUpdated time.Time `json:"last_updated,omitempty"`
}
