/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

type Manufacturer struct {
	Id int32 `json:"id,omitempty"`
	Name string `json:"name"`
	Slug string `json:"slug"`
	Description string `json:"description,omitempty"`
	DevicetypeCount int32 `json:"devicetype_count,omitempty"`
	InventoryitemCount int32 `json:"inventoryitem_count,omitempty"`
	PlatformCount int32 `json:"platform_count,omitempty"`
}
