/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

type WritableVirtualMachineInterface struct {
	Id int32 `json:"id,omitempty"`
	VirtualMachine int32 `json:"virtual_machine,omitempty"`
	Name string `json:"name"`
	Type_ string `json:"type"`
	Enabled bool `json:"enabled,omitempty"`
	Mtu int32 `json:"mtu,omitempty"`
	MacAddress string `json:"mac_address,omitempty"`
	Description string `json:"description,omitempty"`
	Mode string `json:"mode,omitempty"`
	UntaggedVlan int32 `json:"untagged_vlan,omitempty"`
	TaggedVlans []int32 `json:"tagged_vlans,omitempty"`
	Tags []string `json:"tags,omitempty"`
}
