/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.11
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

import (
	"time"
)

type WritablePrefix struct {
	Id int32 `json:"id,omitempty"`
	Url string `json:"url,omitempty"`
	Display string `json:"display,omitempty"`
	Family string `json:"family,omitempty"`
	// IPv4 or IPv6 network with mask
	Prefix string `json:"prefix"`
	Site int32 `json:"site,omitempty"`
	Vrf int32 `json:"vrf,omitempty"`
	Tenant int32 `json:"tenant,omitempty"`
	Vlan int32 `json:"vlan,omitempty"`
	// Operational status of this prefix
	Status string `json:"status,omitempty"`
	// The primary function of this prefix
	Role int32 `json:"role,omitempty"`
	// All IP addresses within this prefix are considered usable
	IsPool bool `json:"is_pool,omitempty"`
	Description string `json:"description,omitempty"`
	Tags []NestedTag `json:"tags,omitempty"`
	CustomFields *interface{} `json:"custom_fields,omitempty"`
	Created string `json:"created,omitempty"`
	LastUpdated time.Time `json:"last_updated,omitempty"`
	Children int32 `json:"children,omitempty"`
	Depth int32 `json:"_depth,omitempty"`
}
