/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

type Graph struct {
	Id int32 `json:"id,omitempty"`
	Type_ string `json:"type"`
	Weight int32 `json:"weight,omitempty"`
	Name string `json:"name"`
	TemplateLanguage string `json:"template_language,omitempty"`
	Source string `json:"source"`
	Link string `json:"link,omitempty"`
}
