/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

type AvailableIp struct {
	Family int32 `json:"family,omitempty"`
	Address string `json:"address,omitempty"`
	Vrf *NestedVrf `json:"vrf,omitempty"`
}
