/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

type FrontPortTemplate struct {
	Id int32 `json:"id,omitempty"`
	DeviceType *NestedDeviceType `json:"device_type"`
	Name string `json:"name"`
	Type_ *Type1 `json:"type"`
	RearPort *NestedRearPortTemplate `json:"rear_port"`
	RearPortPosition int32 `json:"rear_port_position,omitempty"`
}
