/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.11
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

import (
	"time"
)

type Service struct {
	Id int32 `json:"id,omitempty"`
	Url string `json:"url,omitempty"`
	Display string `json:"display,omitempty"`
	Device *NestedDevice `json:"device,omitempty"`
	VirtualMachine *NestedVirtualMachine `json:"virtual_machine,omitempty"`
	Name string `json:"name"`
	Ports []int32 `json:"ports"`
	Protocol *Protocol `json:"protocol,omitempty"`
	Ipaddresses []NestedIpAddress `json:"ipaddresses,omitempty"`
	Description string `json:"description,omitempty"`
	Tags []NestedTag `json:"tags,omitempty"`
	CustomFields *interface{} `json:"custom_fields,omitempty"`
	Created string `json:"created,omitempty"`
	LastUpdated time.Time `json:"last_updated,omitempty"`
}
