/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

import (
	"time"
)

type WritableSecret struct {
	Id int32 `json:"id,omitempty"`
	Device int32 `json:"device"`
	Role int32 `json:"role"`
	Name string `json:"name,omitempty"`
	Plaintext string `json:"plaintext"`
	Hash string `json:"hash,omitempty"`
	Tags []string `json:"tags,omitempty"`
	CustomFields *interface{} `json:"custom_fields,omitempty"`
	Created string `json:"created,omitempty"`
	LastUpdated time.Time `json:"last_updated,omitempty"`
}
