/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

type VirtualMachineInterface struct {
	Id int32 `json:"id,omitempty"`
	VirtualMachine *NestedVirtualMachine `json:"virtual_machine"`
	Name string `json:"name"`
	Type_ *Type7 `json:"type,omitempty"`
	Enabled bool `json:"enabled,omitempty"`
	Mtu int32 `json:"mtu,omitempty"`
	MacAddress string `json:"mac_address,omitempty"`
	Description string `json:"description,omitempty"`
	Mode *Mode `json:"mode,omitempty"`
	UntaggedVlan *NestedVlan `json:"untagged_vlan,omitempty"`
	TaggedVlans []NestedVlan `json:"tagged_vlans,omitempty"`
	Tags []string `json:"tags,omitempty"`
}
