/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.11
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

import (
	"time"
)

type JournalEntry struct {
	Id int32 `json:"id,omitempty"`
	Url string `json:"url,omitempty"`
	Display string `json:"display,omitempty"`
	AssignedObjectType string `json:"assigned_object_type"`
	AssignedObjectId int32 `json:"assigned_object_id"`
	AssignedObject map[string]string `json:"assigned_object,omitempty"`
	Created time.Time `json:"created,omitempty"`
	CreatedBy int32 `json:"created_by,omitempty"`
	Kind *Kind `json:"kind,omitempty"`
	Comments string `json:"comments"`
}
