/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

type NestedInterface struct {
	Id int32 `json:"id,omitempty"`
	Url string `json:"url,omitempty"`
	Device *NestedDevice `json:"device,omitempty"`
	Name string `json:"name"`
	Cable int32 `json:"cable,omitempty"`
	ConnectionStatus *ConnectionStatus `json:"connection_status,omitempty"`
}
