/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

import (
	"time"
)

type IpAddress struct {
	Id int32 `json:"id,omitempty"`
	Family *Family `json:"family,omitempty"`
	// IPv4 or IPv6 address (with mask)
	Address string `json:"address"`
	Vrf *NestedVrf `json:"vrf,omitempty"`
	Tenant *NestedTenant `json:"tenant,omitempty"`
	Status *Status6 `json:"status,omitempty"`
	Role *Role1 `json:"role,omitempty"`
	Interface_ *IpAddressInterface `json:"interface,omitempty"`
	NatInside *NestedIpAddress `json:"nat_inside,omitempty"`
	NatOutside *NestedIpAddress `json:"nat_outside,omitempty"`
	// Hostname or FQDN (not case-sensitive)
	DnsName string `json:"dns_name,omitempty"`
	Description string `json:"description,omitempty"`
	Tags []string `json:"tags,omitempty"`
	CustomFields *interface{} `json:"custom_fields,omitempty"`
	Created string `json:"created,omitempty"`
	LastUpdated time.Time `json:"last_updated,omitempty"`
}
