/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

import (
	"time"
)

type ImageAttachment struct {
	Id int32 `json:"id,omitempty"`
	ContentType string `json:"content_type"`
	ObjectId int32 `json:"object_id"`
	Parent map[string]string `json:"parent,omitempty"`
	Name string `json:"name,omitempty"`
	Image string `json:"image,omitempty"`
	ImageHeight int32 `json:"image_height"`
	ImageWidth int32 `json:"image_width"`
	Created time.Time `json:"created,omitempty"`
}
