/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.11
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

type NestedInterface struct {
	Id int32 `json:"id,omitempty"`
	Url string `json:"url,omitempty"`
	Display string `json:"display,omitempty"`
	Device *NestedDevice `json:"device,omitempty"`
	Name string `json:"name"`
	Cable int32 `json:"cable,omitempty"`
	Occupied string `json:"_occupied,omitempty"`
}
