/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

type WritableConsolePort struct {
	Id int32 `json:"id,omitempty"`
	Device int32 `json:"device"`
	Name string `json:"name"`
	// Physical port type
	Type_ string `json:"type,omitempty"`
	Description string `json:"description,omitempty"`
	ConnectedEndpointType string `json:"connected_endpoint_type,omitempty"`
	//  Return the appropriate serializer for the type of connected object. 
	ConnectedEndpoint map[string]string `json:"connected_endpoint,omitempty"`
	ConnectionStatus bool `json:"connection_status,omitempty"`
	Cable *NestedCable `json:"cable,omitempty"`
	Tags []string `json:"tags,omitempty"`
}
