/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.11
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

import (
	"time"
)

type ConfigContext struct {
	Id int32 `json:"id,omitempty"`
	Url string `json:"url,omitempty"`
	Display string `json:"display,omitempty"`
	Name string `json:"name"`
	Weight int32 `json:"weight,omitempty"`
	Description string `json:"description,omitempty"`
	IsActive bool `json:"is_active,omitempty"`
	Regions []NestedRegion `json:"regions,omitempty"`
	SiteGroups []NestedSiteGroup `json:"site_groups,omitempty"`
	Sites []NestedSite `json:"sites,omitempty"`
	DeviceTypes []NestedDeviceType `json:"device_types,omitempty"`
	Roles []NestedDeviceRole `json:"roles,omitempty"`
	Platforms []NestedPlatform `json:"platforms,omitempty"`
	ClusterGroups []NestedClusterGroup `json:"cluster_groups,omitempty"`
	Clusters []NestedCluster `json:"clusters,omitempty"`
	TenantGroups []NestedTenantGroup `json:"tenant_groups,omitempty"`
	Tenants []NestedTenant `json:"tenants,omitempty"`
	Tags []string `json:"tags,omitempty"`
	Data string `json:"data"`
	Created string `json:"created,omitempty"`
	LastUpdated time.Time `json:"last_updated,omitempty"`
}
