/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

type RearPort struct {
	Id int32 `json:"id,omitempty"`
	Device *NestedDevice `json:"device"`
	Name string `json:"name"`
	Type_ *Type1 `json:"type"`
	Positions int32 `json:"positions,omitempty"`
	Description string `json:"description,omitempty"`
	Cable *NestedCable `json:"cable,omitempty"`
	Tags []string `json:"tags,omitempty"`
}
