/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

type WritablePowerPortTemplate struct {
	Id int32 `json:"id,omitempty"`
	DeviceType int32 `json:"device_type"`
	Name string `json:"name"`
	Type_ string `json:"type,omitempty"`
	// Maximum power draw (watts)
	MaximumDraw int32 `json:"maximum_draw,omitempty"`
	// Allocated power draw (watts)
	AllocatedDraw int32 `json:"allocated_draw,omitempty"`
}
