/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

type WritableConfigContext struct {
	Id int32 `json:"id,omitempty"`
	Name string `json:"name"`
	Weight int32 `json:"weight,omitempty"`
	Description string `json:"description,omitempty"`
	IsActive bool `json:"is_active,omitempty"`
	Regions []int32 `json:"regions,omitempty"`
	Sites []int32 `json:"sites,omitempty"`
	Roles []int32 `json:"roles,omitempty"`
	Platforms []int32 `json:"platforms,omitempty"`
	ClusterGroups []int32 `json:"cluster_groups,omitempty"`
	Clusters []int32 `json:"clusters,omitempty"`
	TenantGroups []int32 `json:"tenant_groups,omitempty"`
	Tenants []int32 `json:"tenants,omitempty"`
	Tags []string `json:"tags,omitempty"`
	Data string `json:"data"`
}
