/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.11
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

type CircuitCircuitTermination struct {
	Id int32 `json:"id,omitempty"`
	Url string `json:"url,omitempty"`
	Display string `json:"display,omitempty"`
	Site *NestedSite `json:"site"`
	ProviderNetwork *NestedProviderNetwork `json:"provider_network"`
	PortSpeed int32 `json:"port_speed,omitempty"`
	// Upstream speed, if different from port speed
	UpstreamSpeed int32 `json:"upstream_speed,omitempty"`
	XconnectId string `json:"xconnect_id,omitempty"`
}
