/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.11
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

type NestedVrf struct {
	Id int32 `json:"id,omitempty"`
	Url string `json:"url,omitempty"`
	Display string `json:"display,omitempty"`
	Name string `json:"name"`
	// Unique route distinguisher (as defined in RFC 4364)
	Rd string `json:"rd,omitempty"`
	DisplayName string `json:"display_name,omitempty"`
	PrefixCount int32 `json:"prefix_count,omitempty"`
}
