/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.11
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

import (
	"time"
)

type ObjectChange struct {
	Id int32 `json:"id,omitempty"`
	Url string `json:"url,omitempty"`
	Display string `json:"display,omitempty"`
	Time time.Time `json:"time,omitempty"`
	User *NestedUser `json:"user,omitempty"`
	UserName string `json:"user_name,omitempty"`
	RequestId string `json:"request_id,omitempty"`
	Action *Action `json:"action,omitempty"`
	ChangedObjectType string `json:"changed_object_type,omitempty"`
	ChangedObjectId int32 `json:"changed_object_id"`
	//  Serialize a nested representation of the changed object. 
	ChangedObject map[string]string `json:"changed_object,omitempty"`
	PrechangeData string `json:"prechange_data,omitempty"`
	PostchangeData string `json:"postchange_data,omitempty"`
}
