/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

type WritablePowerPanel struct {
	Id int32 `json:"id,omitempty"`
	Site int32 `json:"site"`
	RackGroup int32 `json:"rack_group,omitempty"`
	Name string `json:"name"`
	PowerfeedCount int32 `json:"powerfeed_count,omitempty"`
}
