/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.11
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

type WritableCable struct {
	Id int32 `json:"id,omitempty"`
	Url string `json:"url,omitempty"`
	Display string `json:"display,omitempty"`
	TerminationAType string `json:"termination_a_type"`
	TerminationAId int32 `json:"termination_a_id"`
	TerminationA map[string]string `json:"termination_a,omitempty"`
	TerminationBType string `json:"termination_b_type"`
	TerminationBId int32 `json:"termination_b_id"`
	TerminationB map[string]string `json:"termination_b,omitempty"`
	Type_ string `json:"type,omitempty"`
	Status string `json:"status,omitempty"`
	Label string `json:"label,omitempty"`
	Color string `json:"color,omitempty"`
	Length int32 `json:"length,omitempty"`
	LengthUnit string `json:"length_unit,omitempty"`
	Tags []NestedTag `json:"tags,omitempty"`
	CustomFields *interface{} `json:"custom_fields,omitempty"`
}
