/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

type WritableVlanGroup struct {
	Id int32 `json:"id,omitempty"`
	Name string `json:"name"`
	Slug string `json:"slug"`
	Site int32 `json:"site,omitempty"`
	Description string `json:"description,omitempty"`
	VlanCount int32 `json:"vlan_count,omitempty"`
}
