/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

type WritableCircuitTermination struct {
	Id int32 `json:"id,omitempty"`
	Circuit int32 `json:"circuit"`
	TermSide string `json:"term_side"`
	Site int32 `json:"site"`
	PortSpeed int32 `json:"port_speed"`
	// Upstream speed, if different from port speed
	UpstreamSpeed int32 `json:"upstream_speed,omitempty"`
	XconnectId string `json:"xconnect_id,omitempty"`
	PpInfo string `json:"pp_info,omitempty"`
	Description string `json:"description,omitempty"`
	ConnectedEndpointType string `json:"connected_endpoint_type,omitempty"`
	//  Return the appropriate serializer for the type of connected object. 
	ConnectedEndpoint map[string]string `json:"connected_endpoint,omitempty"`
	ConnectionStatus bool `json:"connection_status,omitempty"`
	Cable *NestedCable `json:"cable,omitempty"`
}
