/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.11
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

type WritableCircuitTermination struct {
	Id int32 `json:"id,omitempty"`
	Url string `json:"url,omitempty"`
	Display string `json:"display,omitempty"`
	Circuit int32 `json:"circuit"`
	TermSide string `json:"term_side"`
	Site int32 `json:"site,omitempty"`
	ProviderNetwork int32 `json:"provider_network,omitempty"`
	PortSpeed int32 `json:"port_speed,omitempty"`
	// Upstream speed, if different from port speed
	UpstreamSpeed int32 `json:"upstream_speed,omitempty"`
	XconnectId string `json:"xconnect_id,omitempty"`
	PpInfo string `json:"pp_info,omitempty"`
	Description string `json:"description,omitempty"`
	// Treat as if a cable is connected
	MarkConnected bool `json:"mark_connected,omitempty"`
	Cable *NestedCable `json:"cable,omitempty"`
	//  Return the appropriate serializer for the cable termination model. 
	CablePeer map[string]string `json:"cable_peer,omitempty"`
	CablePeerType string `json:"cable_peer_type,omitempty"`
	Occupied string `json:"_occupied,omitempty"`
}
