/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.11
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

import (
	"time"
)

type InventoryItem struct {
	Id int32 `json:"id,omitempty"`
	Url string `json:"url,omitempty"`
	Display string `json:"display,omitempty"`
	Device *NestedDevice `json:"device"`
	Parent int32 `json:"parent,omitempty"`
	Name string `json:"name"`
	// Physical label
	Label string `json:"label,omitempty"`
	Manufacturer *NestedManufacturer `json:"manufacturer,omitempty"`
	// Manufacturer-assigned part identifier
	PartId string `json:"part_id,omitempty"`
	Serial string `json:"serial,omitempty"`
	// A unique tag used to identify this item
	AssetTag string `json:"asset_tag,omitempty"`
	// This item was automatically discovered
	Discovered bool `json:"discovered,omitempty"`
	Description string `json:"description,omitempty"`
	Tags []NestedTag `json:"tags,omitempty"`
	CustomFields *interface{} `json:"custom_fields,omitempty"`
	Created string `json:"created,omitempty"`
	LastUpdated time.Time `json:"last_updated,omitempty"`
	Depth int32 `json:"_depth,omitempty"`
}
