/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

import (
	"time"
)

type WritablePowerFeed struct {
	Id int32 `json:"id,omitempty"`
	PowerPanel int32 `json:"power_panel"`
	Rack int32 `json:"rack,omitempty"`
	Name string `json:"name"`
	Status string `json:"status,omitempty"`
	Type_ string `json:"type,omitempty"`
	Supply string `json:"supply,omitempty"`
	Phase string `json:"phase,omitempty"`
	Voltage int32 `json:"voltage,omitempty"`
	Amperage int32 `json:"amperage,omitempty"`
	// Maximum permissible draw (percentage)
	MaxUtilization int32 `json:"max_utilization,omitempty"`
	Comments string `json:"comments,omitempty"`
	Tags []string `json:"tags,omitempty"`
	CustomFields *interface{} `json:"custom_fields,omitempty"`
	Created string `json:"created,omitempty"`
	LastUpdated time.Time `json:"last_updated,omitempty"`
}
