/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.11
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

type CustomLink struct {
	Id int32 `json:"id,omitempty"`
	Url string `json:"url,omitempty"`
	Display string `json:"display,omitempty"`
	ContentType string `json:"content_type"`
	Name string `json:"name"`
	// Jinja2 template code for link text
	LinkText string `json:"link_text"`
	// Jinja2 template code for link URL
	LinkUrl string `json:"link_url"`
	Weight int32 `json:"weight,omitempty"`
	// Links with the same group will appear as a dropdown menu
	GroupName string `json:"group_name,omitempty"`
	// The class of the first link in a group will be used for the dropdown button
	ButtonClass string `json:"button_class,omitempty"`
	// Force link to open in a new window
	NewWindow bool `json:"new_window,omitempty"`
}
