/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.8
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

type RackReservation struct {
	Id int32 `json:"id,omitempty"`
	Rack *NestedRack `json:"rack"`
	Units []int32 `json:"units"`
	Created string `json:"created,omitempty"`
	User *NestedUser `json:"user"`
	Tenant *NestedTenant `json:"tenant,omitempty"`
	Description string `json:"description"`
}
