/*
 * NetBox API
 *
 * API to access NetBox
 *
 * API version: 2.11
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package netbox_client

type ExportTemplate struct {
	Id int32 `json:"id,omitempty"`
	Url string `json:"url,omitempty"`
	Display string `json:"display,omitempty"`
	ContentType string `json:"content_type"`
	Name string `json:"name"`
	Description string `json:"description,omitempty"`
	// The list of objects being exported is passed as a context variable named <code>queryset</code>.
	TemplateCode string `json:"template_code"`
	// Defaults to <code>text/plain</code>
	MimeType string `json:"mime_type,omitempty"`
	// Extension to append to the rendered filename
	FileExtension string `json:"file_extension,omitempty"`
	// Download file as attachment
	AsAttachment bool `json:"as_attachment,omitempty"`
}
