name: CI

on:
  push:
    branches:
      - ci

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: checkout ci branch
        uses: actions/checkout@v2
        with:
          ref: refs/heads/ci
          path: ./ci

      - name: checkout master branch
        uses: actions/checkout@v2
        with:
          ref: refs/heads/master
          path: ./master

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: download swagger-codegen-cli.jar
        run: wget https://repo1.maven.org/maven2/io/swagger/swagger-codegen-cli/2.4.15/swagger-codegen-cli-2.4.15.jar -O ./ci/swagger-codegen-cli.jar

      - name: validate swagger file
        run: java -jar ./ci/swagger-codegen-cli.jar validate -i ./ci/netbox_swagger.json

      - name: Build
        run: |
          java -jar ./ci/swagger-codegen-cli.jar generate -l go \
            -c ./ci/config.json \
            -i ./ci/netbox_swagger.json \
            -o ./master

      - name: commit and push generated code
        run: |
          cd ./master
          go mod tidy
          git add .
          if [ -z "$(git status --porcelain)" ]; then
            echo "::debug::no changes to commit and push"
          else
            git config --local user.email "${GITHUB_ACTOR}@github.com"
            git config --local user.name "$GITHUB_ACTOR"
            git commit -m "code generation"
            git push origin master
          fi
